[package]
name = "vellum"
description = "A Markdown-first static blog generator for durable writing"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["blog", "markdown", "static-site"]
categories = ["command-line-utilities"]

[dependencies]
askama.workspace = true
comrak.workspace = true
rayon.workspace = true
syntect.workspace = true

[lints]
workspace = true
